### ISSUE TITLE
golioth_on_message inconsistently bounded by mutex

### ISSUE THREAD

**Issue by vancefarren** [golioth/golioth-zephyr-sdk#115]
bounded by mutex in get sample:
https://github.com/golioth/zephyr-sdk/blob/ff39bf1c51e8185964c7de8b253ca4d657393ca8/samples/lightdb/get/src/main.c#L59

not bounded in observe sample
https://github.com/golioth/zephyr-sdk/blob/ff39bf1c51e8185964c7de8b253ca4d657393ca8/samples/lightdb/observe/src/main.c#L91

**Comment by vancefarren** [comment]
Is this okay?

**Comment by 0Grit** [comment]
@mniestroj

**Comment by mniestroj** [comment]
This issue will be addressed as part of #132.

**Comment by mniestroj** [comment]
`golioth_on_message` was removed.
