### ISSUE TITLE
Better notify user about empty/incorrect PSK/PSK_ID

### ISSUE THREAD

**Issue by mniestroj** [golioth/golioth-zephyr-sdk#146]
### Hardware Target

all

### Golioth Dsdk Commit Hash

309597316d6963832bb777f901e5c869f99daff3

### What Host OS are you using?

Other (Mention Below)

### What happened?

Using empty PSK/PSK_ID results in errors appearing from Zephyr logging subsystem, but there is no clear way what is the source of the problem. We should at least point users into PSK/PSK_ID being invalid, as that is often the case.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vitprajzler** [comment]
The PSK_ID now has a specific format (`[device ID]@[project ID]`), so apart from checking for empty string, we could check for a well formatted PSK_ID.

For example, at least one character of device ID and one character of project ID, with `@` in the middle.

**Comment by mniestroj** [comment]
Implemented in #79
