### ISSUE TITLE
Update SDK to work with NCS 1.8.0

### ISSUE THREAD

**Issue by vitprajzler** [golioth/golioth-zephyr-sdk#158]
The currently supported version of NCS is 1.7.1. 

We should update our SDK to support the latest current version of NCS, 1.8.0.

Reported in #157

**Comment by mniestroj** [comment]
NCS 1.8.0 is broken.

Related issue on Nordic DevZone: https://devzone.nordicsemi.com/f/nordic-q-a/84041/bug-changes-to-nrf91_sockets-c-breaking-native-tls-when-using-libraries
Commit with breaking changes: https://github.com/nrfconnect/sdk-nrf/commit/27e7ebd847222ba0c7dd923add62558ffe57c4aa
