### ISSUE TITLE
FR: Method to query state of Golioth cloud connection

### ISSUE THREAD

**Issue by ramb0t** [golioth/golioth-zephyr-sdk#159]
It would be handy to have a way to query the state of the Golioth cloud connection, connected/disconnected etc. This would helo with usability for the end-user. Then for example we could have status LEDs on a device to show network connectivity and cloud connectivity status and help with debugging troublesome devices by showing potential network issues at a glance.

https://discord.com/channels/819247807662915605/819251195940044800/938741598559305769

**Comment by vitprajzler** [comment]
Good point, added to our backlog.

**Comment by ncmiller** [comment]
This was added in https://github.com/golioth/golioth-zephyr-sdk/pull/226.

https://github.com/golioth/golioth-zephyr-sdk/blob/main/include/net/golioth.h#L162-L172

```
/**
 * @brief Check if client is connected to Golioth
 *
 * Check if client instance is connected to Golioth.
 *
 * @param client Client instance.
 *
 * @retval true When client is connected to Golioth.
 * @retval false When client is not connected to Golioth.
 */
bool golioth_is_connected(struct golioth_client *client);
```

Closing.
