### ISSUE TITLE
Add ESP32 DFU instructions

### ISSUE THREAD

**Issue by szczys** [golioth/golioth-zephyr-sdk#177]
### Describe the feature

The DFU sample works on ESP32, but is not mentioned in the README:
https://github.com/golioth/zephyr-sdk/blob/main/samples/dfu/README.rst

Instructions should be added, or just a link to the blog post:
https://blog.golioth.io/firmware-update-for-esp32-devices/

### Existing feature reference

dfu sample

**Comment by mniestroj** [comment]
We have https://github.com/golioth/golioth-zephyr-sdk/blob/main/samples/dfu/README.rst#esp32 already.
