### ISSUE TITLE
Test & update to use new Zephyr toolchain

### ISSUE THREAD

**Issue by beriberikix** [golioth/golioth-zephyr-sdk#179]
### Describe the feature

https://github.com/zephyrproject-rtos/sdk-ng/releases/tag/v0.14.0

The official toolchain provided by Zephyr was recently migrating to a new packaging and distribution system. This should have no affect on Linux (but we should verify) but introduces official packages for macOS & Windows. This is a significant improvement on the user experience for users on macOS & Windows.

Note: the Espressif toolchain is still separate, but there is a [draft PR](https://github.com/zephyrproject-rtos/sdk-ng/pull/426) that will add it to the new distribution. This will be benefit all three platforms.

**Comment by mniestroj** [comment]
Already using 0.14.2 in CI. Should not have impact on other things (like README files, etc.), so closing this issue.
