### ISSUE TITLE
west.yml FileNotFoundError during west update

### ISSUE THREAD

**Issue by szczys** [golioth/golioth-zephyr-sdk#198]
### Zephyr Commit hash

d51a67b7c098c8bb5479a7b87f05dc40fb76e065

### Golioth SDK Commit Hash

cc65be097d269d8938e4c91222cea63f8099aefb

### Hardware Target

all platforms

### What host OS are you using?

This affects every OS

### Current Behavior

# Known Issue

This is a known issue, we're filing this as a bug to make the fix more visible

Anyone who installed the Golioth SDK prior to May 2022 and tries to update it will see a `FileNotFoundError` for the west.yml when updating their repo and running `west update`.

### Expected Behavior

# How to fix

## Overview

Edit the `config` file in the `<project root>/.west` directory to point to `west-zephyr.yml` (or `west-ncs.yml` if you are using the NCS version of our SDK)

## Steps to fix:

1. Edit `zephyrproject/.west/config`
2. Change `file = west.yml` to `file = west-zephyr.yml`
3. Update west
    ```
    cd ~/zephyrproject/modules/lib/golioth
    git pull
    west update
    ```

### Steps To Reproduce

Start with a Golioth Zephyr SDK installed prior to May 2022

1. `cd ~/zephyrproject/modules/lib/golioth`
2. `git pull`
3. `west update`

### Logs, console output, or any kind of debug information

```shell
$ cd ~/zephyrproject/modules/lib/golioth
$ git pull
$ west update
Traceback (most recent call last):
  File "/home/mike/zephyrproject/.venv/bin/west", line 8, in <module>
    sys.exit(main())
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/app/main.py", line 781, in main
    app.run(argv or sys.argv[1:])
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/app/main.py", line 336, in run_command
    cmd.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/commands.py", line 140, in run
    self.do_run(args, unknown)
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/app/project.py", line 802, in do_run
    self.update_all()
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/app/project.py", line 856, in update_all
    self.manifest = Manifest.from_file(
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/manifest.py", line 1153, in from_file
    return Manifest(**kwargs)
  File "/home/mike/zephyrproject/.venv/lib/python3.8/site-packages/west/manifest.py", line 1283, in __init__
    source_data = source_file.read_text()
  File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/zephyrproject/modules/lib/golioth/west.yml'
```

**Comment by beriberikix** [comment]
I think I ran into the same issue on a fresh install (Raspberry Pi, Aarch64):

```
(.venv) pi@minirack:~ $ west init -m https://github.com/golioth/golioth-zephyr-sdk.git --mr main ~/zephyrproject
=== Initializing in /home/pi/zephyrproject
--- Cloning manifest repository from https://github.com/golioth/golioth-zephyr-sdk.git, rev. main
Cloning into '/home/pi/zephyrproject/.west/manifest-tmp'...
remote: Enumerating objects: 2871, done.
remote: Counting objects: 100% (1074/1074), done.
remote: Compressing objects: 100% (304/304), done.
remote: Total 2871 (delta 852), reused 867 (delta 762), pack-reused 1797
Receiving objects: 100% (2871/2871), 622.87 KiB | 2.76 MiB/s, done.
Resolving deltas: 100% (1750/1750), done.
FATAL ERROR: can't init: no west.yml found in /home/pi/zephyrproject/.west/manifest-tmp
  Hint: check --manifest-url=https://github.com/golioth/golioth-zephyr-sdk.git and --manifest-rev=main  You may need to remove /home/pi/zephyrproject/.west before retrying.
```

**Comment by beriberikix** [comment]
Adding back west.yml fixed the issue: https://github.com/beriberikix/golioth-zephyr-sdk/commit/27ae34b056c267920fff2795826876a756d297c8

**Comment by beriberikix** [comment]
`west init -m https://github.com/golioth/golioth-zephyr-sdk.git --mr main ~/zephyrproject --mf west-zephyr.yml` fixes the issue. It feels a bit clunky and I'd prefer to support the default of west.yml, but at least we have a fix.

**Comment by szczys** [comment]
@beriberikix The new approach to installing the SDK specifies west-zephyr.yml as the manifest file instead of west.yml.

```
west init -m https://github.com/golioth/golioth-zephyr-sdk.git --mr west-zephyr.yml ~/golioth-zephyr-workspace
```

I'll make sure to get that merged into docs on Monday, sorry.

**Comment by beriberikix** [comment]
No worries! You don't need to specify `--mf`?

**Comment by szczys** [comment]
> No worries! You don't need to specify `--mf`?

Yes, I copy pasted incorrectly. Have corrected it above (copied from the SDK readme this time).
