### ISSUE TITLE
Add automated tests of existing features/samples

### ISSUE THREAD

**Issue by 0Grit** [golioth/golioth-zephyr-sdk#92]
So far we have only build tests in CI. Those work well, but they do not check if something was broken in runtime. We need to develop automated tests, which will run whenever we refactor code, add more features or want to test with newer Zephyr (or some library) release.

In the first step it makes most sense to use simulated device (e.g. QEMU, native_posix) to execute SDK samples / tests. This will cover 80-90% of the codebase already. Next step would be to use reference hardware boards officially supported by Golioth. This however requires more effort, but is the only way to increase code coverage of the samples we provide.

Originally reported by @mniestroj

**Comment by 0Grit** [comment]
Related: https://github.com/golioth/zephyr-sdk/issues/35

**Comment by mniestroj** [comment]
Already covered.
